Try to declare 5 different vectors

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import norm
%matplotlib.pylot


In [4]:
A_1 = np.array([4,2,3,1])
A_2 = np.array([5,7,6,8])
A_3 = np.array([9,8,1,5])
A_4 = np.array([6,4,2,7])
A_5 = np.array([7,5,4,6])

Perform the following operations in any combination and any number of trials.

Addition

In [13]:
Addition = A_1 + A_5
print(Addition)

[11  7  7  7]


 Subtraction

In [14]:
Subtraction = A_2 - A_3
print(Subtraction)

[-4 -1  5  3]


Multiplication


In [11]:
Multiplication = A_1 * A_4
print(Multiplication)

[24  8  6  7]


Division

In [17]:
Division = A_2 / A_1
print(Division)

[1.25 3.5  2.   8.  ]


Squaring

In [22]:
A_3=([4,2,3,1])
print(np.square(A_1))

[16  4  9  1]


Square Root

In [32]:
A_3 = ([9,8,1,5])
print(np.sqrt(A_3))

[3.         2.82842712 1.         2.23606798]


Summation

In [27]:
A_S =([4,2,3,1],
[5,7,6,8],
[9,8,1,5],
[6,4,2,7],
[7,5,4,6])

print(np.sum(A_S))

100


Visualize the vectors you have displayed and the results of their operations